name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - php: 7.4
            laravel: "6.*"
            testbench: "^6.0"
          - php: 7.4
            laravel: "7.*"
            testbench: "^6.0"
          - php: 7.4
            laravel: "8.*"
            testbench: "^6.0"
          - php: 8.0
            laravel: "6.*"
            testbench: "^6.0"
          - php: 8.0
            laravel: "7.*"
            testbench: "^6.0"
          - php: 8.0
            laravel: "8.*"
            testbench: "^6.0"
          - php: 8.0
            laravel: "9.*"
            testbench: "^6.0"
          - php: 8.1
            laravel: "6.*"
            testbench: "^6.0"
          - php: 8.1
            laravel: "7.*"
            testbench: "^6.0"
          - php: 8.1
            laravel: "8.*"
            testbench: "^6.0"
          - php: 8.1
            laravel: "9.*"
            testbench: "^6.0"
          - php: 8.1
            laravel: "10.*"
            testbench: "^6.0"
          - php: 8.2
            laravel: "6.*"
            testbench: "^6.0"
          - php: 8.2
            laravel: "7.*"
            testbench: "^6.0"
          - php: 8.2
            laravel: "8.*"
            testbench: "^6.0"
          - php: 8.2
            laravel: "9.*"
            testbench: "^6.0"
          - php: 8.2
            laravel: "10.*"
            testbench: "^6.0"
          - php: 8.2
            laravel: "11.*"
            testbench: "^10.0"
          - php: 8.3
            laravel: "6.*"
            testbench: "^6.0"
          - php: 8.3
            laravel: "7.*"
            testbench: "^6.0"
          - php: 8.3
            laravel: "8.*"
            testbench: "^6.0"
          - php: 8.3
            laravel: "9.*"
            testbench: "^6.0"
          - php: 8.3
            laravel: "10.*"
            testbench: "^6.0"
          - php: 8.3
            laravel: "11.*"
            testbench: "^10.0"

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction
          composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit
