name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1, 8.2]
        laravel: ["6.*", "7.*", "8.*", "9.*", "10.*", "11.*"]
        dependency-version: [prefer-stable]
        include:
          - php: 7.4
            laravel: 8.*
            testbench: 6.*
          - php: 8.0
            laravel: 8.*
            testbench: 6.*
          - php: 8.1
            laravel: 8.*
            testbench: 6.*
          - php: 8.2
            laravel: 8.*
            testbench: 6.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit
